class NotificationModel {
  String? id; // Optional, generated by Firestore or specified manually.
  String notifierId; // The user who pledged a gift.
  String notifiedId; // The user to whom the gift pledge belongs.

  NotificationModel({
    this.id,
    required this.notifierId,
    required this.notifiedId,
  });

  // Converts a Firestore document to a NotificationModel instance.
  factory NotificationModel.fromMap(Map<String, dynamic> map, String documentId) {
    return NotificationModel(
      id: documentId,
      notifierId: map['notifierId'] as String,
      notifiedId: map['notifiedId'] as String,
    );
  }

  // Converts a NotificationModel instance to a map for Firestore.
  Map<String, dynamic> toMap() {
    return {
      'notifierId': notifierId,
      'notifiedId': notifiedId,
    };
  }
}
